- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: windows2016
      location: eastus
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: windows2016
      name: myVnet
      address_prefixes: "10.0.0.0/16"
  - name: Add subnet
    azure_rm_subnet:
      resource_group: windows2016
      name: mySubnet
      address_prefix: "10.0.1.0/24"
      virtual_network: myVnet
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: windows2016
      allocation_method: Static
      name: myPublicIP
    register: output_ip_address
  - name: Dump public IP for VM which will be created
    debug:
      msg: "The public IP is {{ output_ip_address.state.ip_address }}."
  - name: Create Network Security Group that allows winrm
    azure_rm_securitygroup:
      resource_group: windows2016
      name: myNetworkSecurityGroup
      rules:
      - name: 'AllowRDP'          
        protocol: Tcp          
        source_address_prefix: 0.0.0.0/0          
        destination_port_range: 3389          
        access: Allow          
        priority: 100          
        direction: Inbound        
      - name: 'AllowWinRM'          
        protocol: Tcp          
        source_address_prefix: 0.0.0.0/0          
        destination_port_range: 5986          
        priority: 102          
        direction: Inbound        
      - name: 'DenyAll'          
        protocol: Tcp          
        source_address_prefix: 0.0.0.0/0          
        destination_port_range: 0-65535          
        priority: 103          
        direction: Inbound
  - name: Create virtual network interface card
    azure_rm_networkinterface:
      resource_group: windows2016
      name: myNIC
      virtual_network: myVnet
      subnet: mySubnet
      public_ip_name: myPublicIP
      security_group: myNetworkSecurityGroup
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: windows2016
      name: myVM
      vm_size: Standard_DS1_v2
      admin_username: azureuser
      admin_password: carona@202099
      os_type: Windows
      network_interfaces: myNIC
      image:
        offer: WindowsServer
        publisher: MicrosoftWindowsServer
        sku: 2016-Datacenter
        version: latest
